2019-08-29 17:18:38.918 [error] <0.250.0> CRASH REPORT Process <0.250.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'bol_queue' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.264.0>,{call,{'queue.declare',0,<<"bol_queue">>,false,true,false,false,false,[{<<"x-dead-letter-exchange">>,longstr,<<>>},{<<"x-dead-letter-routing-key">>,longstr,<<"bol_queue_error">>}]},none,<0.250.0>},60000]}} in gen_server:call/3 line 223
2019-08-29 17:22:07.352 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'bol_queue' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.328.0>,{call,{'queue.declare',0,<<"bol_queue">>,false,true,false,false,false,[{<<"x-dead-letter-exchange">>,longstr,<<>>},{<<"x-dead-letter-routing-key">>,longstr,<<"bol_queue_error">>}]},none,<0.316.0>},60000]}} in gen_server:call/3 line 223
2019-08-29 17:31:19.539 [error] <0.241.0> CRASH REPORT Process <0.241.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'bol_queue' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.255.0>,{call,{'queue.declare',0,<<"bol_queue">>,false,true,false,false,false,[{<<"x-dead-letter-exchange">>,longstr,<<>>},{<<"x-dead-letter-routing-key">>,longstr,<<"bol_queue_error">>}]},none,<0.241.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 11:58:39.768 [error] <0.49.0> Loading of /Users/adilcjr/Projects/elixir/rabbit_tut/_build/dev/lib/rabbit_tut/ebin/Elixir.RabbitmqCli.Amqp.beam failed: badfile
2019-08-30 11:58:39.769 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.RabbitmqCli.Amqp':
  BEAM file exists but it defines a module named Elixir.RabbitmqCli.AMQP

2019-08-30 11:58:39.770 [error] <0.49.0> Loading of /Users/adilcjr/Projects/elixir/rabbit_tut/_build/dev/lib/rabbit_tut/ebin/Elixir.RabbitmqCli.Amqp.beam failed: badfile
2019-08-30 11:58:39.770 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.RabbitmqCli.Amqp':
  BEAM file exists but it defines a module named Elixir.RabbitmqCli.AMQP

2019-08-30 11:59:29.587 [error] <0.49.0> Loading of /Users/adilcjr/Projects/elixir/rabbit_tut/_build/dev/lib/rabbit_tut/ebin/Elixir.RabbitmqCli.Amqp.beam failed: badfile
2019-08-30 11:59:29.588 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.RabbitmqCli.Amqp':
  BEAM file exists but it defines a module named Elixir.RabbitmqCli.AMQP

2019-08-30 11:59:29.594 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.RabbitmqCli.Amqp':
  BEAM file exists but it defines a module named Elixir.RabbitmqCli.AMQP

2019-08-30 11:59:29.600 [error] <0.49.0> Loading of /Users/adilcjr/Projects/elixir/rabbit_tut/_build/dev/lib/rabbit_tut/ebin/Elixir.RabbitmqCli.Amqp.beam failed: badfile
2019-08-30 14:18:28.178 [error] <0.249.0>@Elixir.Channel:open CRASH REPORT Process <0.249.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.252.0>})
2019-08-30 14:24:32.737 [error] <0.249.0>@Elixir.Channel:open CRASH REPORT Process <0.249.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.252.0>})
2019-08-30 14:34:47.966 [error] <0.240.0>@Elixir.Channel:open CRASH REPORT Process <0.240.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.243.0>})
2019-08-30 14:35:46.846 [error] <0.249.0>@Elixir.Connection:open CRASH REPORT Process <0.249.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.Connection':open(<<"amqp://guest:guest@localhost">>)
2019-08-30 14:36:39.500 [error] <0.249.0>@Elixir.Channel:open CRASH REPORT Process <0.249.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.Channel':open(#{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.252.0>})
2019-08-30 14:38:11.897 [error] <0.249.0> CRASH REPORT Process <0.249.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'bol_exchange' in vhost '/': received 'direct' but current is 'fanout'">>}},{gen_server,call,[<0.263.0>,{call,{'exchange.declare',0,<<"bol_exchange">>,<<"direct">>,false,true,false,false,false,[]},none,<0.249.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:45:31.422 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'bol_exchange' in vhost '/': received 'direct' but current is 'fanout'">>}},{gen_server,call,[<0.254.0>,{call,{'exchange.declare',0,<<"bol_exchange">>,<<"direct">>,false,true,false,false,false,[]},none,<0.240.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:47:05.039 [error] <0.249.0> CRASH REPORT Process <0.249.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'bol_queue' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.263.0>,{call,{'queue.declare',0,<<"bol_queue">>,false,false,true,false,false,[]},none,<0.249.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:49:45.652 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'bol_queue' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.254.0>,{call,{'queue.declare',0,<<"bol_queue">>,false,false,true,false,false,[]},none,<0.240.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:52:38.467 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'bol_ex' in vhost '/': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.254.0>,{call,{'exchange.declare',0,<<"bol_ex">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.240.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:54:56.701 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'bol_ex' in vhost '/': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.254.0>,{call,{'exchange.declare',0,<<"bol_ex">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.240.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:55:49.317 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 1 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'bol_ex' in vhost '/': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.254.0>,{call,{'exchange.declare',0,<<"bol_ex">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.240.0>},60000]}} in gen_server:call/3 line 223
2019-08-30 14:57:04.513 [error] <0.264.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.264.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2019-08-30 14:57:04.514 [error] <0.261.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.261.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.12>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.263.0>, {<<"client 127.0.0.1:64192 -> 127.0.0.1:5672">>,1}) at <0.264.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2019-08-30 14:57:04.514 [error] <0.261.0> Supervisor {<0.261.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.12>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.263.0>, {<<"client 127.0.0.1:64192 -> 127.0.0.1:5672">>,1}) at <0.264.0> exit with reason reached_max_restart_intensity in context shutdown
